-- MySQL Script generated by MySQL Workbench
-- mer. 29 janv. 2020 10:41:03 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema melody
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema melody
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `melody` DEFAULT CHARACTER SET utf8 ;
USE `melody` ;

-- -----------------------------------------------------
-- Table `mydb`.`Profil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melody`.`Profil` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(150) NOT NULL,
  `password` LONGTEXT NOT NULL,
  `role` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melody`.`Challenge` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `sequence` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Status challenge`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `melody`.`Status challenge` (
  `Profil_id` INT NOT NULL,
  `Challenge_id` INT NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`Profil_id`, `Challenge_id`),
  INDEX `fk_Profil_has_Challenge_Challenge1_idx` (`Challenge_id` ASC),
  INDEX `fk_Profil_has_Challenge_Profil_idx` (`Profil_id` ASC),
  CONSTRAINT `fk_Profil_has_Challenge_Profil`
    FOREIGN KEY (`Profil_id`)
    REFERENCES `melody`.`Profil` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profil_has_Challenge_Challenge1`
    FOREIGN KEY (`Challenge_id`)
    REFERENCES `melody`.`Challenge` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
